name: Update Pre-release

on:
  workflow_run:
    workflows: ["Build Desktop"] # Имя твоего workflow билда
    types: [completed]
    branches: [main] # Или другая ветка, на которой ты хочешь обновлять pre-release
  workflow_dispatch:
    inputs:
      build_id:
        description: 'ID успешного Workflow Run из "Build Desktop" (необязательно)'
        required: false
        type: string

jobs:
  update-pre-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Get build details (if triggered manually)
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.build_id != null && github.event.inputs.build_id != '' }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const github = require('@actions/github');
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const run_id_str = ${{ github.event.inputs.build_id }};
            const run_id = parseInt(run_id_str); // Преобразуем строку в число

            if (isNaN(run_id)) {
              console.error('Invalid build ID provided.');
              core.setFailed('Invalid build ID provided.');
              return;
            }

            const run = await github.rest.actions.getWorkflowRun({
              owner,
              repo,
              run_id,
            });

            if (run.data.conclusion !== 'success') {
              console.error(\`Workflow run ${run_id} was not successful. Aborting.\`);
              core.setFailed(\`Workflow run ${run_id} was not successful.\`);
            }

            core.setOutput('commit_sha', run.data.head_commit.id);
            
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
        continue-on-error: true # Чтобы не останавливаться, если какой-то артефакт не найден

      - name: Create or update pre-release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const github = require('@actions/github');
            const fs = require('fs');
            const path = require('path');

            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const commit_sha = github.event.workflow_run.head_commit.id;
            const preReleaseName = 'Windows-CI-build';
            const artifactsPath = 'artifacts';
            const packageVersion = process.env.PACKAGE_VERSION; // Получи версию из env, если она тебе нужна

            const artifactsToUpload = [
              { name: `Bitwarden-Portable-${packageVersion}.exe`, path: path.join(artifactsPath, `Bitwarden-Portable-${packageVersion}.exe`) },
              { name: `Bitwarden-Installer-${packageVersion}.exe`, path: path.join(artifactsPath, `Bitwarden-Installer-${packageVersion}.exe`) },
              { name: `bitwarden-${packageVersion}-ia32.nsis.7z`, path: path.join(artifactsPath, `bitwarden-${packageVersion}-ia32.nsis.7z`) },
              { name: `bitwarden-${packageVersion}-x64.nsis.7z`, path: path.join(artifactsPath, `bitwarden-${packageVersion}-x64.nsis.7z`) },
              { name: `bitwarden-${packageVersion}-arm64.nsis.7z`, path: path.join(artifactsPath, `bitwarden-${packageVersion}-arm64.nsis.7z`) },
              // Добавь YML файл автообновления, если он тебе нужен
            ];

            // Функция для загрузки ассета
            async function uploadAsset(releaseId, filePath) {
              const filename = path.basename(filePath);
              const fileContent = fs.readFileSync(filePath);
              const fileSize = fs.statSync(filePath).size;

              console.log(`Загрузка файла: ${filename} (${fileSize} bytes)`);
              await github.rest.repos.uploadReleaseAsset({
                owner,
                repo,
                release_id: releaseId,
                name: filename,
                data: fileContent,
                headers: {
                  'Content-Type': 'application/octet-stream',
                  'Content-Length': fileSize,
                },
              });
              console.log(`Файл ${filename} успешно загружен.`);
            }

            // Поиск существующего пре-релиза
            const releases = await github.rest.repos.listReleases({ owner, repo });
            const preRelease = releases.data.find(release => release.prerelease && release.name === preReleaseName);

            let releaseId;
            if (preRelease) {
              releaseId = preRelease.id;
              console.log(`Найден существующий пре-релиз с ID: ${releaseId}`);

              // Получение существующих ассетов релиза
              const assets = await github.rest.repos.listReleaseAssets({ owner, repo, release_id });

              // Удаление старых ассетов
              for (const asset of assets.data) {
                console.log(`Удаление старого ассета: ${asset.name} (ID: ${asset.id})`);
                await github.rest.repos.deleteReleaseAsset({ owner, repo, asset_id: asset.id });
                console.log(`Ассет ${asset.name} удален.`);
              }

              // Загрузка новых ассетов
              for (const filePath of filesToUpload) {
                await uploadAsset(releaseId, filePath);
              }
            } else {
              // Создание нового пре-релиза, если он не существует
              const newRelease = await github.rest.repos.createRelease({
                owner,
                repo,
                tag_name: `pre-release-${commit_sha.slice(0, 7)}`, // Можно использовать SHA коммита из build workflow
                name: preReleaseName,
                body: 'Автоматически обновленный пре-релиз.',
                prerelease: true,
                target_commitish: commit_sha, // Или github.event.workflow_run.head_commit.id
              });
              releaseId = newRelease.data.id;
              console.log(`Создан новый пре-релиз с ID: ${releaseId}`);

              // Загрузка ассетов в новый пре-релиз
              for (const filePath of filesToUpload) {
                await uploadAsset(releaseId, filePath);
              }
            }
